
MYSQL_URL: "root:password@tcp(localhost:3306)/notification"
API_PORT: ":8088"
MetaNodeVersion: "0.0.1.0"
DnsLink_: "http://rpc-proxy-sequoia.ibe.app:7080/api/dns/connection-address/"

ParentAddress: "f8d8ffea90386473317caba62db66c3cb047880b" 
NodeConnectionAddress: "node" 
ParentConnectionAddress: "rpc-proxy-sequoia.ibe.app:4200"
ParentConnectionType: "client"
ConnectionAddress_: "0x1eF5a8c5403c5aA1d43a8DC9eD391351012551Cf"
ChainId: 991

StorageAddress: "da7284faC5E804F8b9d71Aa39310f0f86776b51d"
StorageConnectionAddress: "storage"

PrivateKey_: "3bb39dba2f00ec99c40f9475ce8f9e2cc46ed444d444dc82b0be3c779ba6dc5e"
NotiFactoryABIPath: "../abi/notifactory.json"
NotiFactoryAddress: "0xAc623F7D12638B96e57e8CF23AB16333DAc788DE"

NotiHubABIPath: "../abi/notihub.json"
NotiHubAddress: "0x87eD6a493030E4947872c37548A9ed8520c002c9"

NotificationProjectID: "metanode-t"
NotificationCredential: "./config.json"

PathLevelDB: "../db"

APNSPath: "./authkey.p8"
APNSProduction: false
APNSMaxConcurrentPush: 100
APNSKeyID: "68H2HVB6W9"
APNSTeamID: "N93UU6R4YR"
APNSTopic: "com.metanode.main"

ServerPrivateKeyPath: "./private_key"
RpcURL: "https://rpc-proxy-sequoia.ibe.app:8446"